### ISSUE TITLE
QX1, RaspberryPi2, NoMethodError

### ISSUE THREAD

**Issue by abhasmaskey** [kota65535/sony_camera_remote_api#4]
Hi, I came to know about this repository through a google translate of this website:
http://qiita.com/kota65535/items/d51cac913e6b538c0eca

I am very glad that you took the time to write a wrapper library for Sony´s camera remote api. Nice. I followed your wiki page on how to install and used the example code you provided. I am pretty new at this so I wasn´t able to find out the issue. To provide you a background of the hardware I am using, it´s a raspberry pi 2 running raspbian jessie. I have installed Ruby 2.3 on the system while connecting to the QX1 camera.

I get this error when I run the test.rb that I had your example code in:
`$ ruby test.rb`

> 	from /var/lib/gems/2.3.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api/camera_api.rb:34:in `new'

> 	from /var/lib/gems/2.3.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api/camera_api.rb:34:in `block in initialize'

> 	from /var/lib/gems/2.3.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api/retrying.rb:52:in `reconnect_and_retry_inner'

> 	from /var/lib/gems/2.3.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api/retrying.rb:21:in `reconnect_and_retry'

> 	from /var/lib/gems/2.3.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api/camera_api.rb:33:in `initialize'

> 	from /var/lib/gems/2.3.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api.rb:60:in `new'

> 	from /var/lib/gems/2.3.0/gems/sony_camera_remote_api-0.3.1/lib/sony_camera_remote_api.rb:60:in `initialize'

> 	from test.rb:13:in `new'
> 	from test.rb:13:in `<main>'

Since I am more towards the hardware side, would you please let me know what exactly I am missing here?
Much appreciated of your time! great write up btw.
Thanks

**Comment by kota65535** [comment]
Hi abhasmaskey, I'm happy that you are interested in this library.
Would you mind posting the content of "test.rb"? I will try to reproduce it with QX1.

**Comment by abhasmaskey** [comment]
Sure,

So the way approached was to modify the example you had provided on the wiki page:

the test.rb was:
[test.txt](https://github.com/kota65535/sony_camera_remote_api/files/853736/test.txt)



> require 'sony_camera_remote_api'
> 
> ssid = "DIRECT-owQ1:ILCE-QX1"   # SSID of camera
> pass = "fZcoxX1k"               # passphrase
> interface = "wlan0"             # interface by which you connect to the camera
> 
> (#) Connect to the camera
> shelf = SonyCameraRemoteAPI::Shelf.new 'sonycam.shelf'
> shelf.add_and_select ssid, pass, interface
> shelf.connect
> 
> (#) Initialize Camera class instance, with which you can access all camera functions.
> cam = SonyCameraRemoteAPI::Camera.new shelf
> cam.Change_function_to_shoot 'still', 'Single'
> cam.Capture_still


I did nothing but change the ssid and pass. I have put the hashtag in the bracket because the preview showed bold headings for the explanation. 

I have also attached the file here as txt as .rb is not accepted for uploads
My guess is that I did not install ruby properly. I will have a fresh linux installed and work on the process again. 

Let me know what you think when you have the time.
Thanks a lot!

**Comment by abhasmaskey** [comment]
Issue was that I did not install ruby properly
